(function(){function B(p){return z[/\.\/(\w*)\.js/.exec(p)[1]]}var z={lex:{},parser:{},codegen:{},types:{},index:{}};(function(p){function v(b){return c.test(b)}function r(b){return"\n"==b||"\r"==b}function f(b,c,d){var n=0,f=b();if("["!=f&&"]"!=f)throw"Lexical internal error!";d&&d(f);for(c();"="==b();)c(),d&&d(b()),++n;return b()==f?n:-n-1}function t(b,c){var d=b();c();r(b())&&b()!=d&&c()}function q(b,c,d){function n(b){g.push(b)}var g=[];c();for(r(b())&&t(b,c);;){var h=b();switch(h){case null:throw"unfinished long string/comment";
case "]":if(f(b,c,n)==d)return c(),g.splice(-d-1,d+1),g.join("");break;case "\n":case "\r":t(b,c);n("\n");break;default:n(h),c()}}}function u(b,c){for(;;)switch(b()){case "\n":case "\r":case " ":case "\f":case "\t":case "\v":c();break;case "-":c();if("-"!=b())return"-";c();var d=b();if("["==d){var n=f(b,c);if(0<=n){q(b,c,n);break}}for(;d&&"\n"!=d&&"\r"!=d;)c(),d=b();break;case "[":n=f(b,c);if(0<=n)return{id:w.TK_STRING,val:q(b,c,n)};if(-1==n)return"[";throw"invalid long string delimiter";case "=":c();
if("="!=b())return"=";c();return w.TK_EQ;case "<":c();if("="!=b())return"<";c();return w.TK_LE;case ">":c();if("="!=b())return">";c();return w.TK_GE;case "~":c();if("="!=b())return"~";c();return w.TK_NE;case ":":c();if(":"!=b())return":";c(ls);return w.TK_DBCOLON;case '"':case "'":var d=w.TK_STRING,n=b,x=c,h=[],l=n();x();for(var p=void 0;(p=n())!=l;)switch(p){case null:throw"unfinished string";case "\n":case "\r":throw"unfinished string";case "\\":x();p=n();switch(p){case "b":h.push("\b");x();break;
case "f":h.push("\f");x();break;case "n":h.push("\n");x();break;case "r":h.push("\r");x();break;case "t":h.push("\t");x();break;case "v":h.push("\v");x();break;case "\n":case "\r":h.push("\n");t();break;case "\\":case '"':case "'":h.push(p);x();break;case null:throw"unfinished string";case "z":for(x();lisspace(n());)x();break;case "x":throw"esacpe for char code not supported in lua.js yet.";default:if(!g.test(p))throw"invalid escape sequence"+p;throw"esacpe for char code not supported in lua.js yet.";
}break;default:h.push(p),x()}x();n=h.join("");return{id:d,val:n};case ".":c();if("."==b())return c(),"."==b()?(c(),w.TK_DOTS):w.TK_CONCAT;d=b();if(!g.test(d))return".";case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":case "8":case "9":d=w.TK_NUMBER;n=b;x=c;h=n();x();if("0"!=h||"x"!=n()&&"X"!=n()){h=[h];for(l=n();g.test(l)||"."==l;)h.push(l),x(),l=n();n=parseFloat(h.join(""))}else throw x(),Error("Hexadecimal numeric not supported in lua.js yet.");return{id:d,val:n};case null:return w.TK_EOS;
default:d=b();if(y.test(d)){d=b;n=c;for(x=[];v(d());)x.push(d()),n();d=x.join("");return(n=k[d])?n:{id:w.TK_NAME,val:d}}d=b();c();return d}}function l(b){function c(){return n<b.length?b.charAt(n):null}function d(){n<b.length&&++n}var n=0;return function(){return u(c,d)}}p.tokens="<eof> and break do else elseif end false for function goto if in local nil not or repeat return then true until while .. ... == >= <= ~= :: <--orgion-eof> <number> <name> <string> __javascript".split(" ");var k={and:1,"break":2,
"do":3,"else":4,elseif:5,end:6,"false":7,"for":8,"function":9,"goto":10,"if":11,"in":12,local:13,nil:14,not:15,or:16,repeat:17,"return":18,then:19,"true":20,until:21,"while":22,__javascript:34,__js:34},w={TK_EOS:0,TK_AND:1,TK_BREAK:2,TK_DO:3,TK_ELSE:4,TK_ELSEIF:5,TK_END:6,TK_FALSE:7,TK_FOR:8,TK_FUNCTION:9,TK_GOTO:10,TK_IF:11,TK_IN:12,TK_LOCAL:13,TK_NIL:14,TK_NOT:15,TK_OR:16,TK_REPEAT:17,TK_RETURN:18,TK_THEN:19,TK_TRUE:20,TK_UNTIL:21,TK_WHILE:22,TK_CONCAT:23,TK_DOTS:24,TK_EQ:25,TK_GE:26,TK_LE:27,TK_NE:28,
TK_DBCOLON:29,TK_NUMBER:31,TK_NAME:32,TK_STRING:33,TK_JAVASCRIPT:34};p.TK=w;var y=/^[A-Za-z\_]$/,g=/^[0-9]$/,c=/^[0-9A-Za-z\_]$/;p.generator=l;p.lex=function(b){var c=l(b),d=c(),n=c();return{curr:function(){return d},lookAhead:function(){return n},next:function(){d=n;n=c()}}}})(z.lex);(function(p){function v(b){switch(typeof b){case "string":case "number":return b;case "object":return b.id}}function r(b){return"number"==typeof b?C[b]:"object"==typeof b?C[b.id]:b}function f(b){q(b,m.TK_NAME);var c=
b.curr().val;b.next();return{type:"variable",val:c}}function t(b,c){if(v(b.curr())==c)return b.next(),!0}function q(b,c){if(v(b.curr())!=c)throw Error("symbol "+r(c)+" expected!");}function u(b,c){q(b,c);b.next()}function l(b){q(b,m.TK_NAME);var c=b.curr().val;b.next();return c}function k(b){return{type:"const.string",val:l(b)}}function w(b){q(b,m.TK_STRING);var c=b.curr().val;b.next();return{type:"const.string",val:c}}function y(b){b.next();var c=d(b,0);u(b,"]");return c}function g(b){switch(v(b.curr())){case "(":b.next();
if(")"==b.curr())return b.next(),[];var c=n(b);u(b,")");return c;case "{":return[h(b)];case m.TK_STRING:return[w(b)];default:throw Error("function arguments expected, got "+r(b.curr()));}}function c(b){var c;a:switch(c=v(b.curr()),c){case "(":b.next();c=d(b,0);u(b,")");c={type:"expr.brackets",expr:c};break a;case m.TK_NAME:c=f(b);break a;case m.TK_JAVASCRIPT:b.next();c={type:"expr.javascript",args:g(b)};break a;default:throw Error("unexpected symbol "+(C[c]||c));}for(;;)switch(v(b.curr())){case ".":b.next();
var e=k(b);c={type:"expr.index",self:c,key:e};break;case "[":e=y(b);c={type:"expr.index",self:c,key:e};break;case ":":b.next();var e=k(b),n=g(b);c={type:"expr.callMethod",self:c,key:e,args:n};break;case "(":case "{":case m.TK_STRING:n=g(b);c={type:"expr.call",func:c,args:n};break;default:return c}}function b(b){switch(b.curr()){case "+":return 1;case "-":return 2;case "*":return 3;case "/":return 4;case "%":return 5;case "^":return 6;case m.TK_CONCAT:return 7;case m.TK_EQ:return 8;case "<":return 9;
case m.TK_LE:return 10;case m.TK_NE:return 11;case ">":return 12;case m.TK_GE:return 13;case m.TK_AND:return 14;case m.TK_OR:return 15}}function e(b){switch(v(b.curr())){case m.TK_NUMBER:var d=b.curr().val;b.next();return{type:"const.number",val:d};case m.TK_STRING:return w(b);case m.TK_NIL:return b.next(),{type:"const.nil"};case m.TK_TRUE:return b.next(),{type:"const.boolean",val:!0};case m.TK_FALSE:return b.next(),{type:"const.boolean",val:!1};case m.TK_DOTS:return b.next(),{type:"vararg"};case "{":return h(b);
case m.TK_FUNCTION:return b.next(),z(b);default:return c(b)}}function d(c,n){var f,h;a:{switch(c.curr()){case m.TK_NOT:h="uop.not";break a;case "-":h="uop.minus";break a;case "#":h="uop.len";break a}h=void 0}h?(c.next(),f=d(c,I),f={type:"expr.uop",op:h,operand:f}):f=e(c);for(h=b(c);h&&G[h][0]>n;){c.next();var g=d(c,G[h][1]);f={type:"expr.op",op:H[h],left:f,right:g};h=b(c)}return f}function n(b){var c=[];for(c.push(d(b,0));t(b,",");)c.push(d(b,0));return c}function x(b){var c;c=v(b.curr())==m.TK_NAME?
k(b):y(b);u(b,"=");return{type:"field.rec",key:c,val:d(b,0)}}function h(b){u(b,"{");var c=[];do{if("}"==b.curr())break;var e;a:{e=b;var n=e.curr();switch(v(n)){case m.TK_NAME:e="="!=e.lookAhead()?{type:"field.list",val:d(e,0)}:x(e);break a;case "[":e=x(e);break a;default:e={type:"field.list",val:d(e,0)}}}e&&c.push(e)}while(t(b,",")||t(b,";"));u(b,"}");return{type:"expr.constructor",fields:c}}function E(b){switch(b.curr()){case ";":b.next();break;case m.TK_IF:var e={type:"stat.if"},h=e;b.next();var g=
h;g.cond=d(b,0);u(b,m.TK_THEN);for(g.tblock=A(b);t(b,m.TK_ELSEIF);){h.fblock={type:"block",stats:[{type:"stat.if"}]};var h=h.fblock.stats[0],g=b,x=h;x.cond=d(g,0);u(g,m.TK_THEN);x.tblock=A(g)}t(b,m.TK_ELSE)&&(h.fblock=A(b));u(b,m.TK_END);return e;case m.TK_WHILE:return b.next(),e=d(b,0),u(b,m.TK_DO),h=A(b),u(b,m.TK_END),{type:"stat.while",cond:e,block:h};case m.TK_DO:return b.next(),e=A(b),u(b,m.TK_END),e;case m.TK_FOR:b.next();h=l(b);switch(b.curr()){case "=":b.next();g=d(b,0);u(b,",");x=d(b,0);
t(b,",")&&(e=d(b,0));e={type:"stat.fornum",varname:h,from:g,to:x,step:e};break;case ",":case m.TK_IN:for(e=[h];t(b,",");)e.push(l(b));u(b,m.TK_IN);e={type:"stat.forlist",varnames:e,explist:n(b)};break;default:throw"`=` or `in` expected";}u(b,m.TK_DO);e.block=A(b);u(b,m.TK_END);return e;case m.TK_REPEAT:return b.next(),e=A(b),u(b,m.TK_UNTIL),{type:"stat.repeat",until:d(b,0),block:e};case m.TK_FUNCTION:b.next();for(e=f(b);t(b,".");)h=k(b),e={type:"expr.index",self:e,key:h};t(b,":")?(h=k(b),e={type:"stat.method",
self:e,key:h}):e={type:"stat.function",left:e};e.func=z(b);return e;case m.TK_LOCAL:b.next();if(t(b,m.TK_FUNCTION))return{type:"stat.localfunction",name:l(b),func:z(b)};e=[];do e.push(l(b));while(t(b,","));t(b,"=")&&(h=n(b));return{type:"stat.local",names:e,right:h};case m.TK_RETURN:e={type:"stat.return",nret:[]};b.next();F(b)||";"==b.curr()||(e.nret=n(b));for(;t(b,";"););return e;case m.TK_BREAK:return b.next(),{type:"stat.break"};default:e=c(b);if("="==b.curr()||","==b.curr()){for(e=[e];t(b,",");)e.push(c(b));
u(b,"=");b={type:"stat.assignment",lefts:e,right:n(b)}}else{if("expr.call"!=e.type&&"expr.callMethod"!=e.type&&"expr.javascript"!=e.type)throw Error("syntax error, unexpected expr type "+e.type);b={type:"stat.expr",expr:e}}return b}}function F(b){switch(b.curr()){case m.TK_ELSE:case m.TK_ELSEIF:case m.TK_END:case m.TK_EOS:case m.TK_UNTIL:return!0;default:return 0}}function A(b){for(var c=[];!F(b);){if(b.curr()==m.TK_RETURN){c.push(E(b));break}var e=E(b);e&&c.push(e)}return{type:"block",stats:c}}function z(b){u(b,
"(");var c=[];if(")"!=b.curr()){do switch(v(b.curr())){case m.TK_NAME:c.push(l(b));break;case m.TK_DOTS:c.push(m.TK_DOTS);b.next();break;default:throw"<name> or `...` expected";}while(t(b,","))}var e=!1;0<c.length&&c[c.length-1]==m.TK_DOTS&&(c.pop(),e=!0);u(b,")");var d=A(b);u(b,m.TK_END);return{type:"function",args:c,varargs:e,block:d}}var D=B("./lex.js"),J=D.lex,m=D.TK,C=D.tokens,G=[null,[6,6],[6,6],[7,7],[7,7],[7,7],[10,9],[5,4],[3,3],[3,3],[3,3],[3,3],[3,3],[3,3],[2,2],[1,1]],H=[null,"op.add",
"op.minus","op.mul","op.div","op.mod","op.pow","op.concat","op.equal","op.less","op.lessequal","op.notequal","op.great","op.greatequal","op.and","op.or"];p.opname=H;var I=8;p.main=function(b){var c={type:"function",args:[],varargs:!0,block:A(b)};q(b,m.TK_EOS);return c};p.parse=function(b){return p.main(J(b))}})(z.parser);(function(p){function v(c){return"const.number"==c.type?q(c):"l.__checknumber("+f(c)+")"}function r(c){if("vararg"==c.type||"expr.call"==c.type||"expr.callMethod"==c.type)return!0}
function f(c){return r(c)?"("+q(c)+")[0]":q(c)}function t(c){if(c.length&&r(c[c.length-1])){if(1==c.length)return q(c[0]);for(var b=[],e=0;e<c.length-1;e++)b.push(f(c[e]));return"["+b.join(",")+"].concat("+q(c[c.length-1])+")"}b=[];for(e=0;e<c.length;e++)b.push(f(c[e]));return"["+b.join(",")+"]"}function q(c){if(l[c.type])return l[c.type](c);throw Error("Unsupported ast type "+c.type);}function u(c,b){return function(e){function d(e,f){if(e&&e.constructor==Array){for(var h=0;h<e.length;h++)e[h]=d(e[h],
f);return e}if(e&&e.type){var k=c(e,f)||e,l=g[k.type];if(l)for(h=0;h<l.length;h++)k[l[h]]=d(k[l[h]],k);b&&(k=b(k,f)||k);return k}}return d(e)}}var l={},k,w,y;k="\n";w=function(){k+="    "};y=function(){k=k.substr(0,k.length-4)};l["function"]=function(c){return"function("+c.args.join(",")+")"+q(c.block)};l.block=function(c){var b=[];w();for(var e=0;e<c.stats.length;e++)b.push(q(c.stats[e]));y();return k+"{"+b.join("")+k+"}"};l["stat.getvaargs"]=function(c){return k+"var __VA_ARG = Array.prototype.slice.call(arguments, "+
c.argCount+");"};l["stat.expr"]=function(c){return k+q(c.expr)+";"};l["stat.local"]=function(c){if(c.right){if(1==c.names.length)return k+"var "+c.names[0]+" = "+f(c.right[0])+";";for(var b=[],e=0;e<c.names.length;e++)b.push(c.names[e]+" = t["+e+"]");return k+"var t ="+t(c.right)+","+k+b.join(",")+";"}return k+"var "+c.names.join(",")+";"};l["stat.if"]=function(c){var b=k+"if ("+f(c.cond)+")"+q(c.tblock);return c.fblock&&0<c.fblock.stats.length?1==c.fblock.stats.length&&"stat.if"==c.fblock.stats[0].type?
b+"else"+q(c.fblock.stats[0]):b+"else"+q(c.fblock):b};l["stat.fornum"]=function(c){if(c.step){w();var b=k+c.varname+" = "+c.$var+";"+q(c.block)+k+c.$var+" += "+c.$step;y();return k+"var "+c.$var+" = "+v(c.from)+", "+c.$limit+" = "+v(c.to)+", "+c.$step+" = "+v(c.step)+","+c.varname+";"+k+"while (("+c.$step+">0 && "+c.$var+"<="+c.$limit+") || ("+c.$step+"<0 && "+c.$var+">="+c.$limit+")){"+b+k+"}"}return k+"for (var "+c.varname+", "+c.$var+" = "+v(c.from)+", "+c.$limit+" = "+v(c.to)+";("+c.varname+"="+
c.$var+")<="+c.$limit+";++"+c.$var+")"+q(c.block)};l["stat.forlist"]=function(c){w();var b=c.$st,e=[];e.push(k+"var t = "+b+"[0]("+b+"[1],"+b+"[2]);");for(var d=0;d<c.varnames.length;++d)e.push(k+"var "+c.varnames[d]+" = t["+d+"];");e.push(k+"if ("+c.varnames[0]+" == null) break;");e.push(k+b+"[2] = "+c.varnames[0]+";");e.push(q(c.block));y();return k+"var "+b+" = "+t(c.explist)+";"+k+"for (;;)"+k+"{"+e.join("")+k+"}"};l["stat.while"]=function(c){return k+"while ("+f(c.cond)+")"+q(c.block)};l["stat.repeat"]=
function(c){return k+"do "+q(c.block)+"while (!("+f(c.until)+"));"};l["stat.break"]=function(c){return k+"break;"};l.vararg=function(c){return"__VA_ARG"};l["stat.return"]=function(c){var b=c.nret;if(b.length&&r(b[b.length-1]))return k+"return "+t(c.nret);for(var b=[],e=0;e<c.nret.length;e++)b.push(f(c.nret[e]));return k+"return ["+b+"];"};l["stat.assignment"]=function(c){if(1==c.lefts.length){var b=1==c.right.length?f(c.right[0]):t(c.right)+"[0]";if("expr.index"==c.lefts[0].type){var e=c.lefts[0];
return k+"l.__set("+f(e.self)+", "+q(e.key)+", "+b+");"}return k+q(c.lefts[0])+" = "+b+";"}b=[];b.push(k+"var t = "+t(c.right)+";");for(var d=0;d<c.lefts.length;++d)"expr.index"==c.lefts[d].type?(e=c.lefts[d],b.push(k+"l.__set("+f(e.self)+","+q(e.key)+",t["+d+"]);")):b.push(k+q(c.lefts[d])+" = t["+d+"];");return b.join("")};l["expr.index"]=function(c){return"l.__get("+f(c.self)+","+q(c.key)+")"};l["expr.op"]=function(c){var b,e;switch(c.op){case "op.add":b="l.__add";break;case "op.minus":b="l.__sub";
break;case "op.mul":b="l.__mul";break;case "op.div":b="l.__div";break;case "op.mod":b="l.__mod";break;case "op.pow":b="l.__pow";break;case "op.concat":b="l.__concat";break;case "op.equal":b="l.__eq";break;case "op.less":b="l.__lt";break;case "op.lessequal":b="l.__le";break;case "op.notequal":b="l.__neq";break;case "op.great":b="l.__gt";break;case "op.greatequal":b="l.__ge";break;case "op.and":e="&&";break;case "op.or":e="||";break;default:throw Error(c.op+" is not implemented yet.");}if(e)return f(c.left)+
e+f(c.right);if(b)return b+"("+f(c.left)+","+f(c.right)+")"};l["expr.uop"]=function(c){switch(c.op){case "uop.minus":return"l.__unm("+f(c.operand)+")";case "uop.not":return"!("+f(c.operand)+")";case "uop.len":return"l.__len("+f(c.operand)+")";default:throw Error(c.op+" is not implemented yet.");}};l["expr.call"]=function(c){return"l.__call("+f(c.func)+","+t(c.args)+")"};l["expr.callMethod"]=function(c){return"l.__callMethod("+f(c.self)+","+f(c.key)+","+t(c.args)+")"};l["expr.brackets"]=function(c){return r(c.expr)?
f(c.expr):"("+q(c.expr)+")"};l["expr.constructor"]=function(c){if(!c.fields.length)return"l.__newTable()";for(var b=[],e=0;e<c.fields.length;e++){var d=c.fields[e];if("field.list"==d.type)b.push("[0, "+q(d.val)+"]");else if("field.rec"==d.type)b.push("[1, "+q(d.key)+","+q(d.val)+"]");else throw Error("Invalid field type "+d.type);}return"l.__newTable(["+b.join(",")+"])"};l.variable=function(c){return c.val};l["const.string"]=function(c){return c.val?JSON.stringify(c.val):"l.ds"};l["const.number"]=
function(c){return c.val?JSON.stringify(c.val):"l.d0"};l["const.boolean"]=function(c){return JSON.stringify(c.val)};l["const.nil"]=function(c){return"null"};l["expr.javascript"]=function(c){if(1!=c.args.length)throw Error("__javascript should have exactly one arguments.");return"const.string"==c.args[0].type?"("+c.args[0].val+")":"eval("+f(c.args[0])+")"};var g={"expr.uop":["operand"],"expr.op":["left","right"],"stat.assignment":["lefts","right"],"stat.expr":["expr"],"field.list":["val"],"field.rec":["key",
"val"],"expr.constructor":["fields","recs","list"],"stat.if":["cond","tblock","fblock"],"stat.fornum":["from","to","step","block"],"stat.forlist":["explist","block"],"stat.while":["cond","block"],"stat.repeat":["until","block"],"expr.index":["self","key"],"expr.callMethod":["self","key","args"],"expr.call":["func","args"],"expr.brackets":["expr"],"stat.method":["self","key","func"],"stat.function":["left","func"],"stat.localfunction":["func"],"stat.local":["right"],"stat.return":["nret"],"function":["block"],
block:["stats"]};p.traverse=u;p.phases=[];p.postphases=[];p.run=function(c){for(var b=0;b<p.phases.length;b++)c=p.phases[b](c);c=q(c);for(b=0;b<p.postphases.length;b++)c=p.postphases[b](c);return c};(function(){p.phases.push(u(function(c){switch(c.type){case "function":c.varargs&&c.block.stats.unshift({type:"stat.getvaargs",argCount:c.args.length});c=c.block.stats;"stat.return"!=c[c.length-1].type&&c.push({type:"stat.return",nret:[]});break;case "block":for(var b=[],e=0;e<c.stats.length;e++){var d=
c.stats[e];switch(d.type){case "stat.localfunction":b.push({type:"stat.local",names:[d.name]});b.push({type:"stat.assignment",lefts:[{type:"variable",val:d.name}],right:[d.func]});break;case "stat.function":b.push({type:"stat.assignment",lefts:[d.left],right:[d.func]});break;case "stat.method":d.func.args.unshift("self");b.push({type:"stat.assignment",lefts:[{type:"expr.index",self:d.self,key:d.key}],right:[d.func]});break;default:b.push(c.stats[e])}}c.stats=b}}))})();(function(){p.phases.push(function(c){var b=
[],e,d={},f=0;return c=u(function(c){var h;switch(c.type){case "block":h=[];break;case "function":h=c.args;break;case "stat.fornum":h=[c.varname,"$var","$limit","$step"];break;case "stat.forlist":h=c.varnames;h.push("$st");break;case "variable":if(d[c.val]){var g;h=d[c.val];"fornum"==e.curr.type||"forlist"==e.curr.type?h[h.length-1]!=e.curr?g=h[h.length-1]:1<h.length&&(g=h[h.length-2]):g=h[h.length-1];if(g){c.val=c.val+"$"+g.id;return}}return"_ENV"==c.val?void 0:{type:"expr.index",self:{type:"variable",
val:"_ENV"},key:{type:"const.string",val:c.val}}}if(h){e&&b.push(e);e={curr:c,names:h.slice(0)};for(g=0;g<h.length;g++){var k=h[g];d[k]=d[k]||[];var l=++f;h[g]=k+"$"+l;d[k].push({id:l,curr:c})}"stat.fornum"==c.type?(c.varname=h[0],c.$var=h[1],c.$limit=h[2],c.$step=h[3]):"stat.forlist"==c.type&&(c.$st=h.pop())}},function(c){if(e&&e.curr==c){for(var h=0;h<e.names.length;h++){var g=e.names[h];d[g].pop();0==d[g].length&&delete d[g]}e=b.pop()}else if("stat.local"==c.type)for(h=0;h<c.names.length;h++){g=
c.names[h];d[g]=d[g]||[];var k=d[g];if(0<k.length&&k[k.length-1]===e){var l=k[k.length-1].id=++f;c.names[h]=g+"$"+l}else l=++f,c.names[h]=g+"$"+l,k.push({id:l,curr:e.curr}),e.names.push(g)}})(c)})})();(function(){p.postphases.push(function(c){return"(function(_ENV, l){return "+c+";})"})})();p.sign="/*lua.js generated code*/";(function(){p.postphases.push(function(c){return"/*lua.js generated code*/"+c})})()})(z.codegen);(function(p){function v(f){this.stringMap={};this.array=[];this.hashMap={};this.metatable=
null;this._hashKey=++r;if(f)for(var p=0;p<f.length;p++){var q=f[p];"0"==q[0]?this.array.push(q[1]):this.set(q[1],q[2])}}var r=0;p.LuaTable=v;p.newHashKey=function(){return++r};v.prototype={};v.prototype.constructor=v;v.prototype.get=function(f){if(null==f)throw Error("table index is nil");switch(typeof f){case "number":return this.array[f-1];case "string":return this.stringMap[f];case "object":case "function":return f._hashKey||(f._hashKey=++r),this.hashMap[f._hashKey][1];default:throw Error("get with a invalid argument"+
f);}};v.prototype.set=function(f,p){if(null==f)throw Error("table index is nil");if(null==p)switch(typeof f){case "number":f==this.array.length?this.array.pop():delete this.array[f-1];break;case "string":delete this.stringMap[f];break;case "object":case "function":if(!f._hashKey)break;delete this.hashMap[f._hashKey];break;default:throw Error("set with a invalid argument"+f);}else switch(typeof f){case "number":this.array[f-1]=p;break;case "string":this.stringMap[f]=p;break;case "object":case "function":f._hashKey||
(f._hashKey=++r);this.hashMap[f._hashKey]=[f,p];break;default:throw Error("set with a invalid argument"+f);}};v.prototype.length=function(){for(var f=this.array.length;0<f&&null==this.array[f-1];--f);f!=this.array.length&&(this.array.length=f);return this.array.length};v.prototype.toString=function(){return"table "+this._hashKey}})(z.types);(function(p){function v(b){return b.substr(0,u.length)!=u?q.run(t.parse(b)):b}function r(b,c){var d=g.__getmetatable(b);return d&&d.stringMap&&d.stringMap[c]}
function f(b,c){g[b]=function(d,f){var k=g.__tonumber(d),h=g.__tonumber(f);if(k&&h)return c(k,h)||l;if(k=r(d,b)||r(f,b))return k(d,f)[0];throw Error("attempt to perform arithmetic on a "+g.__type(d)+" value");}}var t=B("./parser.js");p.parser=t;var q=B("./codegen.js");p.codegen=q;var u=q.sign;p.compile=v;var l={valueOf:function(){return 0},toString:function(){return"0"}},k={toString:function(){return""}},w=B("./types.js");p.types=w;var y=new w.LuaTable;p._G=y;var g={};p.helpers=g;g.d0=l;g.ds=k;var c=
new w.LuaTable;y.set("string",c);g.__getmetatable=function(b){if(!b)return null;switch(typeof b){case "object":return b.metatable;case "string":return c;default:return null}};g.__get=function(b,c){var d;if("table"==g.__type(b)){if(d=b.get(c))return d;d=r(b,"__index");if(!d)return null}else if(d=r(b,"__index"),!d)throw Error("attempt to index a "+g.__type(b)+" value.");return"function"==typeof d?d(b,c)[0]:g.__get(d,c)};g.__set=function(b,c,d){var f;if("table"==g.__type(b)){if(b.get(c)){b.set(c,d);
return}f=r(b,"__newindex");if(!f){b.set(c,d);return}}else if(f=r(b,"__newindex"),!f)throw Error("attempt to index a "+g.__type(b)+" value.");"function"==typeof f?f(b,c,d):g.__set(f,c,d)};f("__add",function(b,c){return b+c});f("__mul",function(b,c){return b*c});f("__sub",function(b,c){return b-c});f("__div",function(b,c){return b/c});f("__mod",function(b,c){return b/c});f("__pow",function(b,c){return Math.pow(b,c)});g.__unm=function(b){var c=g.__tonumber(b);if(c)return-c;if(c=r(b).__unm)return c(b)[0];
throw Error("attempt to perform arithmetic on a "+g.__type(b)+" value");};g.__eq=function(b,c){return!g.__neq(b,c)};g.__neq=function(b,c){if(b===c)return!1;var d=g.__type(b),f=g.__type(c);if(d!=f||"table"!=d&&"userdata"!=d)return!0;d=r(b,"__eq");f=r(c,"__eq");return d&&d==f?!d(b,c)[0]:!0};g.__gt=function(b,c){return g.__lt(c,b)};g.__ge=function(b,c){return g.__le(c,b)};g.__lt=function(b,c){var d=g.__type(b),f=g.__type(c);if("number"==d&&"number"==f||"string"==d&&"string"==f)return b<c;if(d=r(b,"__lt")||
r(b,"__lt"))return!!d(b,c)[0];throw Error("attempt to compare "+g.__type(b)+" with "+g.__type(c));};g.__le=function(b,c){var d=g.__type(b),f=g.__type(c);if("number"==d&&"number"==f||"string"==d&&"string"==f)return b<=c;if(d=r(b,"__le")||r(b,"__le"))return!!d(b,c)[0];if(d=r(b,"__lt")||r(b,"__lt"))return!d(c,b)[0];throw Error("attempt to compare "+g.__type(b)+" with "+g.__type(c));};g.__concat=function(b,c){var d=g.__type(b),f=g.__type(c);if(!("number"!=d&&"string"!=d||"number"!=f&&"string"!=f))return""+
b+c||k;if(d=r(b,"__concat")||r(c,"__concat"))return d(b,c)[0];throw Error("attempt to concatenate a "+g.__type(b)+" value");};g.__newTable=function(b){return new w.LuaTable(b)};g.__len=function(b){switch(typeof b){case "string":return b.length}var c=r(b,"__len");if(c)return c(a)[0];if(b.constructor==w.LuaTable)return b.length();throw Error("attempt to get length of a "+g.__type(a)+" value");};g.__tonumber=function(b){switch(typeof b){case "number":return b;case "string":try{return parseInt(s)||l}catch(c){break}default:if(b==
l)return b}return null};g.__checknumber=function(b){switch(typeof b){case "number":return b;case "string":try{return parseInt(s)}catch(c){}}if(b==l)return b;throw Error("Not a number.");};g.__tostring=function(b){if(null==b)return"nil";switch(typeof b){case "number":case "boolean":return b.toString();case "string":return b;case "function":return b._hashKey=b._hashKey||w.newHashKey(),"function("+b._hashKey+")";case "object":if(b==l)return"0";if(b==k)return k;var c=r(b,"__tostring");if(c)return c(b)[0];
if(b.toString)return b.toString();default:return"userdata("+b+")"}};g.__type=function(b){if(null==b)return"nil";var c=typeof b;switch(c){case "number":case "boolean":case "string":case "function":return c;case "object":if(b==l)return"number";if(b==k)return k;if(b.constructor==w.LuaTable)return"table";default:return"userdata"}};g.__call=function(b,c){if("function"==typeof b)return b.apply(null,c);var d=r(b,"__call");if(d)return c.unshift(d),d(c);throw Error("attempt to call a "+g.__type(a)+" value");
};g.__callMethod=function(b,c,d){d.unshift(b);g.__call(g.__get(b,c),d)};p.loadString=function(b){b=v(b);return eval(b)(y,g)}})(z.index);window.luajs=z.index})();
